PKG_CHECK_MODULES(PC_LIBSODIUM libsodium)
FIND_PATH(LIBSODIUM_INCLUDE_DIRS NAMES sodium.h
    HINTS ${PC_LIBSODIUM_INCLUDE_DIRS} ${PC_LIBSODIUM_INCLUDEDIR}
)

FIND_LIBRARY(LIBSODIUM_LIBRARIES NAMES sodium
    HINTS ${PC_LIBSODIUM_LIBRARY_DIRS} ${PC_LIBSODIUM_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibSodium DEFAULT_MSG LIBSODIUM_INCLUDE_DIRS LIBSODIUM_LIBRARIES)
