PKG_CHECK_MODULES(PC_CAIRO cairo>=1.12.0)
FIND_PATH(CAIRO_INCLUDE_DIRS NAMES cairo.h
    HINTS ${PC_CAIRO_INCLUDE_DIRS} ${PC_CAIRO_INCLUDEDIR}
)

FIND_LIBRARY(CAIRO_LIBRARIES NAMES cairo
    HINTS ${PC_CAIRO_LIBRARY_DIRS} ${PC_CAIRO_LIBDIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Cairo DEFAULT_MSG CAIRO_INCLUDE_DIRS CAIRO_LIBRARIES)
